server:
  port: 8088

spring:
  application:
    name: configs
  cloud:
    config:
      server:
        git:
          uri: https://github.com/supEr-attraction/throwng-config.git
          username: throwng-token
          password: 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
          search-paths: /..
          default-label: master
