version: '3.1'

services:
  back-notification:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: dev
    ports:
      - '8082:8082'

networks:
  default:
    external:
      name: connect-default