version: '3.1'

services:
  back-user:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: prod
    ports:
      - '8096:8096'


networks:
  default:
    external:
      name: connect-default