version: '3.1'

services:
  back-user:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: prod
    ports:
      - '8096:8096'
    volumes:
      - /home/ubuntu/pinpoint-agent-2.2.2:/pinpoint

networks:
  default:
    external:
      name: connect-default