version: '3.1'

services:
  back-quiz:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: prod
    ports:
      - '8085:8085'
    volumes:
      - /home/ubuntu/pinpoint-agent-2.2.2:/pinpoint


networks:
  default:
    external:
      name: connect-default