version: '3.1'

services:
  fe:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      #- '5173:4173'
      - '5173:3000'

networks:
  default:
    external:
      name: connect-default