name: Deploy to Batch component

on:
  push:
    branches: ["master", "setting/#27"]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back/batch

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          build-root-directory: ./back/batch

      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Build With Gradle
        run: ./gradlew build

      

      
